/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 10/05/2018 14:17:09
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            64000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLDSIFreq_Value                     500000000
#define MX_SYSCLKFreq_VALUE                     390000000
#define MX_HCLKFreq_Value                       195000000
#define MX_CortexFreq_Value                     390000000
#define MX_APB1Freq_Value                       97500000
#define MX_APB2Freq_Value                       97500000
#define MX_CECFreq_Value                        32000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        390000000
#define MX_WatchDogFreq_Value                   32000
#define MX_DSIFreq_Value                        96000000
#define MX_DSIPHYCLKFreq_Value                  96000000
#define MX_DSITXEscFreq_Value                   20000000
#define MX_SPDIFRXFreq_Value                    390000000
#define MX_MCO1PinFreq_Value                    64000000
#define MX_MCO2PinFreq_Value                    390000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Stream1_IRQn */
#define MX_DMA1_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream1_IRQn_Subriority         0

/* NVIC DMA1_Stream2_IRQn */
#define MX_DMA1_Stream2_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream2_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream2_IRQn_Subriority         0

/* NVIC DMA1_Stream0_IRQn */
#define MX_DMA1_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream0_IRQn_Subriority         0

/*-------------------------------- ETH        --------------------------------*/

#define MX_ETH                                  1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ETH_REF_CLK_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_ETH_REF_CLK_Pin                      PA1
#define MX_ETH_REF_CLK_GPIOx                    GPIOA
#define MX_ETH_REF_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_RMII_REF_CLK                         ETH_REF_CLK
#define MX_ETH_REF_CLK_GPIO_Pin                 GPIO_PIN_1
#define MX_ETH_REF_CLK_GPIO_AF                  GPIO_AF11_ETH
#define MX_ETH_REF_CLK_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PA7 */
#define MX_ETH_CRS_DV_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_ETH_CRS_DV_Pin                       PA7
#define MX_ETH_CRS_DV_GPIOx                     GPIOA
#define MX_ETH_CRS_DV_GPIO_PuPd                 GPIO_NOPULL
#define MX_RMII_CRS_DV                          ETH_CRS_DV
#define MX_ETH_CRS_DV_GPIO_Pin                  GPIO_PIN_7
#define MX_ETH_CRS_DV_GPIO_AF                   GPIO_AF11_ETH
#define MX_ETH_CRS_DV_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PC4 */
#define MX_ETH_RXD0_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD0_Pin                         PC4
#define MX_ETH_RXD0_GPIOx                       GPIOC
#define MX_ETH_RXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_RMII_RXD0                            ETH_RXD0
#define MX_ETH_RXD0_GPIO_Pin                    GPIO_PIN_4
#define MX_ETH_RXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC5 */
#define MX_ETH_RXD1_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD1_Pin                         PC5
#define MX_ETH_RXD1_GPIOx                       GPIOC
#define MX_ETH_RXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_RMII_RXD1                            ETH_RXD1
#define MX_ETH_RXD1_GPIO_Pin                    GPIO_PIN_5
#define MX_ETH_RXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG11 */
#define MX_ETH_TX_EN_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_ETH_TX_EN_Pin                        PG11
#define MX_ETH_TX_EN_GPIOx                      GPIOG
#define MX_ETH_TX_EN_GPIO_PuPd                  GPIO_NOPULL
#define MX_RMII_TX_EN                           ETH_TX_EN
#define MX_ETH_TX_EN_GPIO_Pin                   GPIO_PIN_11
#define MX_ETH_TX_EN_GPIO_AF                    GPIO_AF11_ETH
#define MX_ETH_TX_EN_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA2 */
#define MX_ETH_MDIO_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDIO_Pin                         PA2
#define MX_ETH_MDIO_GPIOx                       GPIOA
#define MX_ETH_MDIO_GPIO_PuPd                   GPIO_NOPULL
#define MX_RMII_MDIO                            ETH_MDIO
#define MX_ETH_MDIO_GPIO_Pin                    GPIO_PIN_2
#define MX_ETH_MDIO_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_MDIO_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB13 */
#define MX_ETH_TXD1_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD1_Pin                         PB13
#define MX_ETH_TXD1_GPIOx                       GPIOB
#define MX_ETH_TXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_RMII_TXD1                            ETH_TXD1
#define MX_ETH_TXD1_GPIO_Pin                    GPIO_PIN_13
#define MX_ETH_TXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG13 */
#define MX_ETH_TXD0_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD0_Pin                         PG13
#define MX_ETH_TXD0_GPIOx                       GPIOG
#define MX_ETH_TXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_RMII_TXD0                            ETH_TXD0
#define MX_ETH_TXD0_GPIO_Pin                    GPIO_PIN_13
#define MX_ETH_TXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC1 */
#define MX_ETH_MDC_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDC_Pin                          PC1
#define MX_ETH_MDC_GPIOx                        GPIOC
#define MX_ETH_MDC_GPIO_PuPd                    GPIO_NOPULL
#define MX_RMII_MDC                             ETH_MDC
#define MX_ETH_MDC_GPIO_Pin                     GPIO_PIN_1
#define MX_ETH_MDC_GPIO_AF                      GPIO_AF11_ETH
#define MX_ETH_MDC_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- MDMA       --------------------------------*/

#define MX_MDMA                                 1

/*-------------------------------- QUADSPI    --------------------------------*/

#define MX_QUADSPI                              1

/* GPIO Configuration */

/* Pin PF10 */
#define MX_QUADSPI_CLK_GPIO_Speed               GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_CLK_Pin                      PF10
#define MX_QUADSPI_CLK_GPIOx                    GPIOF
#define MX_QUADSPI_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_QUADSPI_CLK_GPIO_Pin                 GPIO_PIN_10
#define MX_QUADSPI_CLK_GPIO_AF                  GPIO_AF9_QUADSPI
#define MX_QUADSPI_CLK_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PB6 */
#define MX_QUADSPI_BK1_NCS_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_NCS_GPIO_FM6             __NULL
#define MX_QUADSPI_BK1_NCS_Pin                  PB6
#define MX_QUADSPI_BK1_NCS_GPIOx                GPIOB
#define MX_QUADSPI_BK1_NCS_GPIO_PuPd            GPIO_PULLUP
#define MX_QUADSPI_BK1_NCS_GPIO_Pin             GPIO_PIN_6
#define MX_QUADSPI_BK1_NCS_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_NCS_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF6 */
#define MX_QUADSPI_BK1_IO3_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO3_Pin                  PF6
#define MX_QUADSPI_BK1_IO3_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO3_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO3_GPIO_Pin             GPIO_PIN_6
#define MX_QUADSPI_BK1_IO3_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO3_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF7 */
#define MX_QUADSPI_BK1_IO2_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO2_Pin                  PF7
#define MX_QUADSPI_BK1_IO2_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO2_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO2_GPIO_Pin             GPIO_PIN_7
#define MX_QUADSPI_BK1_IO2_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO2_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF9 */
#define MX_QUADSPI_BK1_IO1_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO1_Pin                  PF9
#define MX_QUADSPI_BK1_IO1_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO1_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO1_GPIO_Pin             GPIO_PIN_9
#define MX_QUADSPI_BK1_IO1_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_IO1_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF8 */
#define MX_QUADSPI_BK1_IO0_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO0_Pin                  PF8
#define MX_QUADSPI_BK1_IO0_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO0_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO0_GPIO_Pin             GPIO_PIN_8
#define MX_QUADSPI_BK1_IO0_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_IO0_GPIO_Mode            GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA MDMA_Channel0_QUADSPI_FIFO_TH_0 */
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_MaskAddress 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Instance MDMA_Channel0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_TransferTriggerMode MDMA_BUFFER_TRANSFER
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SourceDataSize MDMA_SRC_DATASIZE_BYTE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DestBurst MDMA_DEST_BURST_SINGLE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DestBlockAddressOffset 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_pNewNode 
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DestDataSize MDMA_DEST_DATASIZE_BYTE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Endianness MDMA_LITTLE_ENDIANNESS_PRESERVE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DMA_Handle 
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SourceInc MDMA_SRC_INC_BYTE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_BlockCount 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DstAddress 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DataAlignment MDMA_DATAALIGN_PACKENABLE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_BlockDataLength 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_BufferTransferLength 16
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DestinationInc MDMA_DEST_INC_DISABLE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SourceBurst MDMA_SOURCE_BURST_SINGLE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Priority MDMA_PRIORITY_VERY_HIGH
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Request MDMA_REQUEST_QUADSPI_FIFO_TH
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Rank First
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_MaskData 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_IpInstance 
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_CircularMode MDMA_LINEAR_LIST
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_node 
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SourceBlockAddressOffset 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SrcAddress 0

/* NVIC Configuration */

/* NVIC QUADSPI_IRQn */
#define MX_QUADSPI_IRQn_interruptPremptionPriority 0
#define MX_QUADSPI_IRQn_PriorityGroup           NVIC_PRIORITYGROUP_4
#define MX_QUADSPI_IRQn_Subriority              0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS-SWDIO_Pin                   PA13
#define MX_TMS                                  SYS_JTMS-SWDIO

/* Pin PA14 */
#define MX_SYS_JTCK-SWCLK_Pin                   PA14
#define MX_TCK                                  SYS_JTCK-SWCLK

/* Pin PB3 */
#define MX_SYS_JTDO-SWO_Pin                     PB3
#define MX_SWO                                  SYS_JTDO-SWO

/*-------------------------------- TIM1       --------------------------------*/

#define MX_TIM1                                 1

/* GPIO Configuration */

/* Pin PE13 */
#define MX_S_TIM1_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH3_GPIO_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_S_TIM1_CH3_Pin                       PE13
#define MX_S_TIM1_CH3_GPIOx                     GPIOE
#define MX_S_TIM1_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM1_CH3_GPIO_Pin                  GPIO_PIN_13
#define MX_S_TIM1_CH3_GPIO_AF                   GPIO_AF1_TIM1

/* Pin PE12 */
#define MX_TIM1_CH3N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM1_CH3N_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_TIM1_CH3N_Pin                        PE12
#define MX_TIM1_CH3N_GPIOx                      GPIOE
#define MX_TIM1_CH3N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM1_CH3N_GPIO_Pin                   GPIO_PIN_12
#define MX_TIM1_CH3N_GPIO_AF                    GPIO_AF1_TIM1

/* DMA Configuration */

/* DMA TIM1_CH3 */
#define MX_TIM1_CH3_DMA_Instance                DMA1_Stream2
#define MX_TIM1_CH3_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_TIM1_CH3_DMA_Priority                DMA_PRIORITY_LOW
#define MX_TIM1_CH3_DMA_MemDataAlignment        DMA_MDATAALIGN_HALFWORD
#define MX_TIM1_CH3_DMA_Mode                    DMA_NORMAL
#define MX_TIM1_CH3_DMA_SyncRequestNumber       1
#define MX_TIM1_CH3_DMA_Request                 DMA_REQUEST_TIM1_CH3
#define MX_TIM1_CH3_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_TIM1_CH3_DMA_Direction               DMA_PERIPH_TO_MEMORY
#define MX_TIM1_CH3_DMA_SignalID                
#define MX_TIM1_CH3_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_TIM1_CH3_DMA_IpInstance              
#define MX_TIM1_CH3_DMA_RequestNumber           1
#define MX_TIM1_CH3_DMA_EventEnable             DISABLE
#define MX_TIM1_CH3_DMA_SyncEnable              DISABLE
#define MX_TIM1_CH3_DMA_DMA_Handle              
#define MX_TIM1_CH3_DMA_PeriphDataAlignment     DMA_PDATAALIGN_HALFWORD
#define MX_TIM1_CH3_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_TIM1_CH3_DMA_SyncSignalID            
#define MX_TIM1_CH3_DMA_PeriphInc               DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC TIM1_TRG_COM_IRQn */
#define MX_TIM1_TRG_COM_IRQn_interruptPremptionPriority 0
#define MX_TIM1_TRG_COM_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_TIM1_TRG_COM_IRQn_Subriority         0

/* NVIC TIM1_UP_IRQn */
#define MX_TIM1_UP_IRQn_interruptPremptionPriority 0
#define MX_TIM1_UP_IRQn_PriorityGroup           NVIC_PRIORITYGROUP_4
#define MX_TIM1_UP_IRQn_Subriority              0

/* NVIC TIM1_BRK_IRQn */
#define MX_TIM1_BRK_IRQn_interruptPremptionPriority 0
#define MX_TIM1_BRK_IRQn_PriorityGroup          NVIC_PRIORITYGROUP_4
#define MX_TIM1_BRK_IRQn_Subriority             0

/* NVIC TIM1_CC_IRQn */
#define MX_TIM1_CC_IRQn_interruptPremptionPriority 0
#define MX_TIM1_CC_IRQn_PriorityGroup           NVIC_PRIORITYGROUP_4
#define MX_TIM1_CC_IRQn_Subriority              0

/*-------------------------------- UART4      --------------------------------*/

#define MX_UART4                                1

#define MX_UART4_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PA11 */
#define MX_UART4_RX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART4_RX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_RX_Pin                         PA11
#define MX_UART4_RX_GPIOx                       GPIOA
#define MX_UART4_RX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART4_RX_GPIO_Pin                    GPIO_PIN_11
#define MX_UART4_RX_GPIO_AF                     GPIO_AF6_UART4

/* Pin PA12 */
#define MX_UART4_TX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART4_TX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_TX_Pin                         PA12
#define MX_UART4_TX_GPIOx                       GPIOA
#define MX_UART4_TX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART4_TX_GPIO_Pin                    GPIO_PIN_12
#define MX_UART4_TX_GPIO_AF                     GPIO_AF6_UART4

/* DMA Configuration */

/* DMA UART4_RX */
#define MX_UART4_RX_DMA_Instance                DMA1_Stream0
#define MX_UART4_RX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART4_RX_DMA_Priority                DMA_PRIORITY_MEDIUM
#define MX_UART4_RX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART4_RX_DMA_Mode                    DMA_NORMAL
#define MX_UART4_RX_DMA_SyncRequestNumber       1
#define MX_UART4_RX_DMA_Request                 DMA_REQUEST_UART4_RX
#define MX_UART4_RX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART4_RX_DMA_Direction               DMA_PERIPH_TO_MEMORY
#define MX_UART4_RX_DMA_SignalID                
#define MX_UART4_RX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART4_RX_DMA_IpInstance              
#define MX_UART4_RX_DMA_RequestNumber           1
#define MX_UART4_RX_DMA_EventEnable             DISABLE
#define MX_UART4_RX_DMA_SyncEnable              DISABLE
#define MX_UART4_RX_DMA_DMA_Handle              
#define MX_UART4_RX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART4_RX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART4_RX_DMA_SyncSignalID            
#define MX_UART4_RX_DMA_PeriphInc               DMA_PINC_DISABLE

/* DMA UART4_TX */
#define MX_UART4_TX_DMA_Instance                DMA1_Stream1
#define MX_UART4_TX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART4_TX_DMA_Priority                DMA_PRIORITY_MEDIUM
#define MX_UART4_TX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART4_TX_DMA_Mode                    DMA_NORMAL
#define MX_UART4_TX_DMA_SyncRequestNumber       1
#define MX_UART4_TX_DMA_Request                 DMA_REQUEST_UART4_TX
#define MX_UART4_TX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART4_TX_DMA_Direction               DMA_MEMORY_TO_PERIPH
#define MX_UART4_TX_DMA_SignalID                
#define MX_UART4_TX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART4_TX_DMA_IpInstance              
#define MX_UART4_TX_DMA_RequestNumber           1
#define MX_UART4_TX_DMA_EventEnable             DISABLE
#define MX_UART4_TX_DMA_SyncEnable              DISABLE
#define MX_UART4_TX_DMA_DMA_Handle              
#define MX_UART4_TX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART4_TX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART4_TX_DMA_SyncSignalID            
#define MX_UART4_TX_DMA_PeriphInc               DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC UART4_IRQn */
#define MX_UART4_IRQn_interruptPremptionPriority 0
#define MX_UART4_IRQn_PriorityGroup             NVIC_PRIORITYGROUP_4
#define MX_UART4_IRQn_Subriority                0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC13 */
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_USER_Btn_[B1]                        PC13
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_ModeDefaultEXTI            GPIO_MODE_IT_RISING

/* Pin PB14 */
#define MX_PB14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB14_Pin                             PB14
#define MX_PB14_GPIOx                           GPIOB
#define MX_PB14_PinState                        GPIO_PIN_RESET
#define MX_PB14_GPIO_PuPd                       GPIO_NOPULL
#define MX_LD3_[Red]                            PB14
#define MX_PB14_GPIO_Pin                        GPIO_PIN_14
#define MX_PB14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PB7 */
#define MX_PB7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB7_Pin                              PB7
#define MX_PB7_GPIOx                            GPIOB
#define MX_PB7_PinState                         GPIO_PIN_RESET
#define MX_PB7_GPIO_PuPd                        GPIO_NOPULL
#define MX_LD2_[Blue]                           PB7
#define MX_PB7_GPIO_Pin                         GPIO_PIN_7
#define MX_PB7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP
#define MX_PB7_GPIO_FM7                         __NULL

#endif  /* __MX_DEVICE_H */

